version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    environment:
      PIPENV_VENV_IN_PROJECT:

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pipenv sync --dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run linters
          command: |
            pipenv run pylint scraping_foreign_principals
            pipenv run black --check -Sl 80 scraping_foreign_principals

      - run:
          name: run tests
          command: |
            pipenv check
            pipenv run python scraping_foreign_principals/tests.py
            rm scraping_foreign_principals/test_responses/results.json
            pipenv run scrapy crawl principals -o scraping_foreign_principals/test_responses/results.json 2>/dev/null
            pipenv run python scraping_foreign_principals/tests.py
